In [1]:
import pandas as pd

In [2]:
s=pd.Series()
print(s)

Series([], dtype: float64)


C:\Users\ADMIN\AppData\Local\Temp\ipykernel_15064\2242303654.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s=pd.Series()


In [37]:
list1=[1,2,3,4]
s=pd.Series(list1)
s

0    1
1    2
2    3
3    4
dtype: int64

In [38]:
dist1={
    "branch":"CSE",
    "Div":"A",
    "RollNo":24
}
p=pd.Series(dist1)
p

branch    CSE
Div         A
RollNo     24
dtype: object

In [10]:
list2=[4,3,2,1]
l1=[1,2,3,4]
d=pd.Series(list2)
a=pd.Series(l1)
print(a+d)

0    5
1    5
2    5
3    5
dtype: int64


In [11]:
print(len(s))

3


In [13]:
print(s.ndim)

1


In [20]:
b=a.drop(1)
print(b)
print(a)

0    1
2    3
3    4
dtype: int64
0    1
1    2
2    3
3    4
dtype: int64


In [ ]:
#===============================================================================================================================
#===============================================================================================================================

In [21]:
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [23]:
d1={
    'name':["rakesh","kumar","singh","yadav"],
    'm1':[20,30,40,60],
    "m2":[50,60,70,10]
}
df=pd.DataFrame(d1)
print(df)

     name  m1  m2
0  rakesh  20  50
1   kumar  30  60
2   singh  40  70
3   yadav  60  10


In [24]:
df

name  m1  m2
0  rakesh  20  50
1   kumar  30  60
2   singh  40  70
3   yadav  60  10

In [27]:
df.head(2)

name  m1  m2
0  rakesh  20  50
1   kumar  30  60

In [28]:
df.tail(1)

name  m1  m2
3  yadav  60  10

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    4 non-null      object
 1   m1      4 non-null      int64 
 2   m2      4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes


In [31]:
df.shape

(4, 3)

In [32]:
df['m1']

0    20
1    30
2    40
3    60
Name: m1, dtype: int64

In [35]:
df['total']=df['m1']+df['m2']
df


name  m1  m2  total
0  rakesh  20  50     70
1   kumar  30  60     90
2   singh  40  70    110
3   yadav  60  10     70

In [43]:
df.drop('total',axis=1) # 1 means column ( drop delete temporary)

name  m1  m2
0  rakesh  20  50
1   kumar  30  60
2   singh  40  70
3   yadav  60  10

In [44]:
df.drop(2,axis=0) # 0 means row

name  m1  m2  total
0  rakesh  20  50     70
1   kumar  30  60     90
3   yadav  60  10     70

In [42]:
df

name  m1  m2  total
0  rakesh  20  50     70
1   kumar  30  60     90
2   singh  40  70    110
3   yadav  60  10     70

In [51]:
df.drop(2,axis=0,inplace=True)  # permanantly delete
df


name  m1  m2  total
0  rakesh  20  50     70
1   kumar  30  60     90
3   yadav  60  10     70

In [53]:
df.loc[:,'name']

0    rakesh
1     kumar
3     yadav
Name: name, dtype: object

In [55]:
df.iloc[:,0:2]  # works on row and 2nd column

name  m1
0  rakesh  20
1   kumar  30
3   yadav  60

In [56]:
df.drop_duplicates()

name  m1  m2  total
0  rakesh  20  50     70
1   kumar  30  60     90
3   yadav  60  10     70

In [57]:
df.all() # if null values then return false

name     True
m1       True
m2       True
total    True
dtype: bool

In [58]:
df.m1.unique()

array([20, 30, 60], dtype=int64)

In [59]:
df.m1.mean()

36.666666666666664

df.m1.min()

In [60]:
df.m1.min()

20

In [61]:
df.m1.max()

60

In [62]:
df.m1.median()

30.0

In [63]:
df.m1.mode()

0    20
1    30
2    60
Name: m1, dtype: int64

In [64]:
df.at[3,'m1']

60

In [68]:
df.count(0)  # count no. of rows

m1       3
m2       3
total    3
dtype: int64

In [66]:
df.count(1) #count no of column

0    4
1    4
3    4
dtype: int64

In [67]:
del df['name']

In [69]:
df

m1  m2  total
0  20  50     70
1  30  60     90
3  60  10     70

In [70]:
df<0

m1     m2  total
0  False  False  False
1  False  False  False
3  False  False  False

In [71]:
df>0

m1    m2  total
0  True  True   True
1  True  True   True
3  True  True   True

In [73]:
df['m1']>50

0    False
1    False
3     True
Name: m1, dtype: bool

In [74]:
print(df[(df['m1']>20) & (df['m2']>40)])

   m1  m2  total
1  30  60     90


In [76]:
df.sort_values(by=['m1'],ascending=[True],inplace=True)

In [77]:
df

m1  m2  total
0  20  50     70
1  30  60     90
3  60  10     70

In [78]:
df['m1'].groupby

<bound method Series.groupby of 0    20
1    30
3    60
Name: m1, dtype: int64>

In [81]:
df.rename(columns={"m1":"maths1","m2":"maths2"},inplace=True)
df

maths1  maths2  total
0      20      50     70
1      30      60     90
3      60      10     70

In [82]:
#================================================================================================================
#===============================================================================================================

In [83]:
import numpy as np

In [84]:
list4=[1,2,3,4,5]

In [85]:
a2=np.array(list1)

In [86]:
print(list4)
print(a2)

[1, 2, 3, 4, 5]
[1 2 3 4]


In [87]:
print(a2+2)

[3 4 5 6]


In [90]:
b2=np.arange(7) # create array of 7 elemets
print(b2)

[0 1 2 3 4 5 6]


In [91]:
print(b2**2)

[ 0  1  4  9 16 25 36]


In [96]:
np.random.random((2,2))

array([[0.34147052, 0.71737536],
       [0.46164168, 0.90344078]])

In [101]:
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [100]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])